### GET request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "ALok",
  "email": "test@example",
  "address": "123 main st",
  "dateOfBrith": "1990-01-01",
  "registeredDate": "2023-01-01"
}

###