### update an existing patient entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "ALok22",
  "address": "123 main st",
  "email": "test_updated@example",
  "dateOfBrith": "1990-01-01"
}

###